# Generated by Django 5.0.7 on 2024-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_article_article_img_alter_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Onaylı mı?"),
        ),
    ]
