# Generated by Django 5.0.7 on 2024-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_footersettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="footersettings",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="E-posta"),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
        ),
    ]
